"""empty message

Revision ID: b11581ce1e48
Revises: 5375a0719207
Create Date: 2023-02-28 15:45:25.149408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11581ce1e48'
down_revision = '5375a0719207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint('character_eye_color_key', type_='unique')
        batch_op.drop_constraint('character_height_key', type_='unique')
        batch_op.drop_constraint('character_skin_color_key', type_='unique')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint('planet_climate_key', type_='unique')
        batch_op.drop_constraint('planet_gravity_key', type_='unique')
        batch_op.drop_constraint('planet_rotation_period_key', type_='unique')
        batch_op.drop_constraint('planet_surface_water_key', type_='unique')
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_constraint('vehicle_crew_key', type_='unique')
        batch_op.drop_constraint('vehicle_passengers_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.create_unique_constraint('vehicle_passengers_key', ['passengers'])
        batch_op.create_unique_constraint('vehicle_crew_key', ['crew'])

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('planet_surface_water_key', ['surface_water'])
        batch_op.create_unique_constraint('planet_rotation_period_key', ['rotation_period'])
        batch_op.create_unique_constraint('planet_gravity_key', ['gravity'])
        batch_op.create_unique_constraint('planet_climate_key', ['climate'])

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.create_unique_constraint('character_skin_color_key', ['skin_color'])
        batch_op.create_unique_constraint('character_height_key', ['height'])
        batch_op.create_unique_constraint('character_eye_color_key', ['eye_color'])

    # ### end Alembic commands ###
