"""empty message

Revision ID: c1eaf4bec9dc
Revises: b11581ce1e48
Create Date: 2023-02-28 16:21:20.526359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1eaf4bec9dc'
down_revision = 'b11581ce1e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav_char',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('char_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['char_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('fav_car')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav_car',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('char_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['char_id'], ['character.id'], name='fav_car_char_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fav_car_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='fav_car_pkey')
    )
    op.drop_table('fav_char')
    # ### end Alembic commands ###
